# Generated by Django 5.2.1 on 2025-05-28 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0002_rename_user_profile_username_profile_nickname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='user',
        ),
    ]
