# Generated by Django 5.2.1 on 2025-05-28 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0003_rename_username_profile_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='views',
            new_name='likes',
        ),
        migrations.AddField(
            model_name='answer',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
